SmartCanteenSI/Controllers/HomePageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SmartCanteenSI.Controllers
{
    public class HomePageController : Controller    {
        // GET: HomePage
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Logout()
        {
            Session.Clear();
            Session.Abandon();
            return RedirectToAction("Index");
        }
    }
}

SmartCanteenSI/Controllers/LoginController.cs
using SmartCanteenSI.Models;
using SmartCanteenSI.Models.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Security.Principal;
using System.Text;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using static System.Net.WebRequestMethods;

namespace SmartCanteenSI.Controllers
{
    public class LoginController : Controller
    {
        SmartCanteenContext context = new SmartCanteenContext();
        public int OTP = 0;
        public ActionResult LoginPage()
        {
            return View();
        }
        public JsonResult Register(User account)
        {
            string result = "NotExist";
            string adminMail = "misteranonymous2711@gmail.com";
            User checkmail = context.Users.Where(x => x.Email == account.Email).FirstOrDefault();
            if (checkmail == null && account.Email != adminMail)
            {
                account.Role = "User";
                account.IsValid = false;
                account.PassWord = BCrypt.Net.BCrypt.HashPassword(account.PassWord);
                account.Image = "/images/Avatar/pngtree-black-default-avatar-png-image_5407174.jpg";
                context.Users.Add(account);
                context.SaveChanges();
                BuildEmailTemplate((int)account.UserID);
            }
            else if (checkmail != null)
            {
                result = "Exist";
            }
            else if (account.Email == adminMail)
            {
                result = "notAdmin";
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Validate(int regId)
        {
            ViewBag.regID = regId;
            return View();
        }
        public JsonResult RegisterValidate(int regId)
        {
            User Data = context.Users.Where(x => x.UserID == regId).FirstOrDefault();
            Data.IsValid = true;
            context.SaveChanges();
            var msg = "Email của bạn đã được xác thực!";
            return Json(msg, JsonRequestBehavior.AllowGet);
        }
        public void BuildEmailTemplate(int regID)
        {
            string body = System.IO.File.ReadAllText(HostingEnvironment.MapPath("/EmailTemplate/") + "Template" + ".cshtml");
            var regInfo = context.Users.Where(x => x.UserID == regID).FirstOrDefault();
            var url = "https://localhost:44305/" + "Login/Validate?regId=" + regID;
            body = body.Replace("@ViewBag.ConfirmationLink", url);
            body = body.ToString();
            BuildEmailTemplate("Tài khoản của bạn được tạo thành công!", body, regInfo.Email);
        }

        public static void BuildEmailTemplate(string subjectText, string bodyText, string sendTo)
        {
            string from, to, bcc, cc, subject, body;
            from = "witherdragonlair@gmail.com";
            to = sendTo.Trim();
            bcc = "";
            cc = "";
            subject = subjectText;
            StringBuilder sb = new StringBuilder();
            sb.Append(bodyText);
            body = sb.ToString();
            MailMessage mail = new MailMessage();
            mail.From = new MailAddress(from);
            mail.To.Add(new MailAddress(to));
            if (!string.IsNullOrEmpty(bcc))
            {
                mail.Bcc.Add(new MailAddress(bcc));
            }
            if (!string.IsNullOrEmpty(cc))
            {
                mail.CC.Add(new MailAddress(cc));
            }
            mail.Subject = subject;
            mail.Body = body;
            mail.IsBodyHtml = true;
            SendMail(mail);
        }

        public static void SendMail(MailMessage mail)
        {
            SmtpClient client = new SmtpClient();
            client.Host = "smtp.gmail.com";
            client.Port = 587;
            client.EnableSsl = true;
            client.UseDefaultCredentials = false;
            client.DeliveryMethod = SmtpDeliveryMethod.Network;
            client.Credentials = new System.Net.NetworkCredential("witherdragonlair@gmail.com", "wsemqzzmqcuzxtjz");
            try
            {
                client.Send(mail);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        public JsonResult CheckAccount(User model)
        {
            string result = "Fail";
            var checkAccount = context.Users.Where(x => x.Email == model.Email).FirstOrDefault();
            
            if (checkAccount != null)
            {
                bool verified = BCrypt.Net.BCrypt.Verify(model.PassWord, checkAccount.PassWord);
                if (verified == true)
                {
                    if (checkAccount.Email == model.Email && checkAccount.IsValid == true)
                    {
                        Session["Account"] = checkAccount;
                        Session["UserID"] = checkAccount.UserID.ToString();
                        Session["UserName"] = checkAccount.UserName.ToString();
                        Session["Image"] = checkAccount.Image.ToString();
                        Session["Role"]=checkAccount.Role.ToString();
                        result = "Success";
                    }
                    var isValid = checkAccount.IsValid;
                    if (isValid == false)
                    {
                        result = "notValid";
                    }
                }
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public JsonResult SendOTP(User user)
        {

            bool Valid = false;
            User checkEmail = context.Users.SingleOrDefault(x => x.Email == user.Email);
            if (checkEmail != null)
            {
                if (checkEmail.IsValid == false)
                {
                    return Json(Valid, JsonRequestBehavior.AllowGet);
                }
                Valid = true;
                Random rand = new Random();
                OTP = rand.Next(100000, 1000000);
                Session["OTP"] = OTP.ToString();
                var fromAddress = new MailAddress("witherdragonlair@gmail.com");
                var toAddress = new MailAddress(user.Email);
                const string fromPass = "wsemqzzmqcuzxtjz";
                const string subject = "OTP code";
                string body = "Đây là mã xác thực của bạn:\nVui lòng không chia sẻ mã này cho bất kì ai khác:\n" + "\t" + OTP.ToString();
                var smtp = new SmtpClient
                {
                    Host = "smtp.gmail.com",
                    Port = 587,
                    EnableSsl = true,
                    DeliveryMethod = SmtpDeliveryMethod.Network,
                    UseDefaultCredentials = false,
                    Credentials = new NetworkCredential(fromAddress.Address, fromPass),
                    Timeout = 200000
                };
                using (var message = new MailMessage(fromAddress, toAddress)
                {
                    Subject = subject,
                    Body = body,
                })
                {
                    smtp.Send(message);
                }
            }

            return Json(Valid, JsonRequestBehavior.AllowGet);
        }
        public JsonResult ResetPass(User user, FormCollection collection)
        {
            var otp = collection["OTP"];
            string kq = "NotValid";
            var checkMail = context.Users.SingleOrDefault(x => x.Email == user.Email);
            if (Session["OTP"] == null)
            {
                kq = "WrongOTP";
            }
            else if (checkMail != null && otp == Session["OTP"].ToString())
            {
                kq = "Valid";
                checkMail.PassWord = BCrypt.Net.BCrypt.HashPassword(user.PassWord);
                context.SaveChanges();
                Session.Clear();
                Session.Abandon();
            }
            else if (otp != Session["OTP"].ToString())
            {
                kq = "WrongOTP";
            }
            return Json(kq, JsonRequestBehavior.AllowGet);
        }

    }
}

SmartCanteenSI/Controllers/MenuController.cs
using SmartCanteenSI.Models.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace SmartCanteenSI.Controllers
{
    public class MenuController : Controller
    {
        SmartCanteenContext context=new SmartCanteenContext();
        // GET: Menu
        public ActionResult FoodMenu(int? page)
        {
            if (page == null)
            {
                page = 1;
            }
            var allDishes = (from ss in context.Dishes select ss).OrderBy(m => m.DishID);
            int pageSize = 4;//mỗi trang 2 món
            int pageNum = page ?? 1;
            return View(allDishes.ToPagedList(pageNum, pageSize));
        }
    }
}

SmartCanteenSI/Views/Shared/_HomePageLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/HomePageStyle/MainStyle.css" rel="stylesheet" />
    <link href="~/Content/FooterStyle/footer.css" rel="stylesheet" />
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.6.3.min.js"></script>
    <!-- font awesome cdn link  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
</head>

<body>
    @* ----------------------------------------------------------------------------------------------------------------------------*@
    <div class="sticky-top">
        <div class="header-1">
            <a class="logo" href="@Url.Action("Index", "HomePage")">
                <img src="~/images/HomePage/b3a4c58af11fd982867403e74fb9885b--knifes-forks.jpg" />
            </a>

            <div class="navbar-url">
                <a>@Html.ActionLink("Trang Chủ", "Index", "HomePage")</a>
                <a>@Html.ActionLink("Giới thiệu", "About", "Home")</a>
                <a>@Html.ActionLink("Món Ăn", "FoodMenu", "Menu")</a>
            </div>
            <div class="navbar-cart">
                @Html.Partial("~/Views/Cart/CartPartial.cshtml")

            </div>
            @if (Session["Account"] != null)
            {
                <div class="navbar-user">
                    <nav>
                        <img class="user-pic" src="@Session["Image"]" width="48" height="48" onclick="toggleMenu()" />
                        <div class="sub-menu-wrap" id="subMenu">
                            <div class="sub-menu">
                                <div class="user-info">
                                    <img src="@Session["Image"]" width="100" height="100" />
                                    <h2>@Session["UserName"]</h2>
                                </div>
                                <hr>
                                @if (Session["Role"].ToString() == "Admin")
                                {
                                    <div id="manage" class="sub-menu-link" style="cursor: pointer;" onclick="Manage()">
                                        <img src="~/images/UserProfile/setting.png" />
                                        <span style="text-align:left;">Quản lý SmartCanteen</span>
                                    </div>
                                }
                                <div class="sub-menu-link" style="cursor: pointer;" onclick="EditProfile()">
                                    <img src="~/images/UserProfile/profile.png" />
                                    <span style="text-align:left;">Cập nhật thông tin</span>
                                </div>
                                <div class="sub-menu-link" style="cursor: pointer;" onclick="LogOut()">
                                    <img src="~/images/UserProfile/logout.png" />
                                    <span style="text-align:left;">Đăng xuất</span>
                                </div>
                            </div>
                        </div>
                    </nav>
                </div>
            }
            else
            {
                <div class="navbar-user">
                    <nav>
                        <a>@Html.ActionLink("Đăng nhập", "LoginPage", "Login")</a>
                    </nav>
                </div>
            }
            </div>
        </div>

    @* ----------------------------------------------------------------------------------------------------------------------------*@

<div class="container" style="height: 100vh;">
    @RenderBody()
    <hr>
    <footer>
        <div class="boxfooter1">
            <h4>FOLLOW US</h4>
            <div class="logo-footer">
                <img src="~/images/icon/facebook.jpg" />
                <img src="~/images/icon/insta.jpg" />
            </div>
        </div>
        <div class="boxfooter2">
            <h4>ABOUT US</h4>
            <div class="add2">Bui Minh Nhat - 2011060734</div>
            <div class="add2">Huynh Phuoc Dat - 2011062086</div>
            <div class="add2">Vo Phan Truong Nguyen - 2011061720</div>
        </div>
        <div class="boxfooter3">
            <h4>CONTACT US</h4>
            <div class="add">Phone Number 1: 0901234565</div>
            <div class="add">Phone Number 2: 0988778567</div>
        </div>
    </footer>

</div>


        <script>
        var subMenu = document.getElementById("subMenu");
        function toggleMenu() {
            subMenu.classList.toggle("open-menu");
        }
        function LogOut() {
            if (confirm("Bạn có chắc muốn đăng xuất!") == true) {
                alert("Đã đăng xuất!")
                window.location.href = "/HomePage/Logout";
            } else {
                return false;
            }
        }
        function EditProfile() {
            window.location.href = "/User/EditProfile";
        }
        </script>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
        @RenderSection("upload", required: false)
</body>

</html>

SmartCanteenSI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container" style="height: 101vh;">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>